spring:
  application:
    name: wms
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localdb
    username: sa
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6379
  h2:
    console:
      enabled: true
