### Register Order

POST http://localhost:8080/order/v1/orders
Content-Type: application/json

{
  "orderItems": [
    {
      "productId": "ac5720dc-90fb-4891-aa9d-910248f9fd25",
      "quantity": 1
    },
    {
      "productId": "6efce639-3a34-46e0-9658-24f3e8d502be",
      "quantity": 2
    }
  ],
  "orderer": {
    "ordererName": "홍길동",
    "address": {
      "postalCode": "12345",
      "city": "성남시",
      "district":  "수정구",
      "streetAddress": "street-address",
      "addressDetail":  "address-detail"
    }
  },
  "channelType": "TEAM_FRESH_MALL"
}
